<?php

/**
 * Returns the new skin settings merged with the old skin settings so ensure no setting is left blank
 * @param array $settings 
 * @return none or array $settings
 * @since 1.0
 */
function cuttz_back_compat( $settings = array() ) {
	if ( !is_array( $settings ) || empty( $settings ) ) {
		return;
	}
	$cuttz_skin_defaults = cuttz_skin_defaults();
	$updated                = wp_parse_args( $settings, $cuttz_skin_defaults );
	return $updated;
}

/**
 * Enqueue Semantic UI styles and scripts in Cuttz to support Semantic UI integration
 * @return null
 * @since 1.1
 */
function cuttz_semantic_ui(){
	wp_enqueue_style( 'cuttz-semantic-ui', get_stylesheet_directory_uri() . '/lib/semantic-ui/semantic.min.css', array(), false, 'all' );
	wp_enqueue_script( 'cuttz-semantic-ui', get_stylesheet_directory_uri() . '/lib/semantic-ui/semantic.min.js', array(), false, true );
}

/**
 * Returns the slug of the Cuttz skin settings options page.
 * @return string
 * @since 1.0
 */
function cuttz_get_skin_page_id() {
	$customization = genesis_get_option( 'skin', CHILD_SETTINGS_FIELD_EXTRAS, false );
	if ( empty( $customization ) ) {
		$customization = 'vanilla';
	}
	return CHILD_SETTINGS_FIELD . '-' . $customization;
}

/**
 * Returns the name of the skin
 * @return string
 * @since 1.0
 */
function cuttz_get_skin_page_title() {
	$customization      = genesis_get_option( 'skin', CHILD_SETTINGS_FIELD_EXTRAS, false );
	$all_customizations = cuttz_customization_aggregator();
	if ( is_array( $all_customizations ) && array_key_exists( $customization, $all_customizations ) ) {
		return $all_customizations[$customization]['name'];
	}
}

/**
 * Builds and returns a list of all available skins in Cuttz
 * @return array
 * @since 1.0
 */
function cuttz_customization_aggregator() {
	$core_customizations = glob( CUTTZ_CORE_SKINS . '/*', GLOB_ONLYDIR );
	$user_customizations = glob( CUTTZ_USER_SKINS . '/*', GLOB_ONLYDIR );
	$extns               = array(
		'png',
		'gif',
		'jpg',
		'jpeg'
	);
	$extns               = apply_filters( 'cuttz_screenshot_types', $extns );
	if ( is_array( $core_customizations ) ) {
		foreach ( $core_customizations as $customization ) {
			if ( !file_exists( $customization . '/functions.php' ) && !file_exists( $customization . '/style.css' ) && !file_exists( $customization . '/style.scss' ) ) {
				continue;
			}
			$name                            = preg_replace( '/[^A-Za-z0-9\-\s]/', '', basename( $customization ) );
			$name                            = str_replace( '-', ' ', $name );
			$name                            = ucwords( strtolower( $name ) );
			$id                              = cuttz_ws( basename( $customization ) );
			$all_customizations[$id]         = array(
				'name' => $name
			);
			$all_customizations[$id]['type'] = 'core';
			$all_customizations[$id]['dir']  = str_replace( ' ', '%20', $customization );
			$all_customizations[$id]['url']  = str_replace( ' ', '%20', CUTTZ_CORE_SKINS_URL . '/' . basename( $customization ) );
			if ( file_exists( $customization . '/autogenerated.css' ) ) {
				$all_customizations[$id]['style'] = str_replace( ' ', '%20', CUTTZ_CORE_SKINS_URL . '/' . basename( $customization ) . '/autogenerated.css' );
			}
			if ( file_exists( $customization . '/style.scss' ) ) {
				$all_customizations[$id]['sass'] = str_replace( ' ', '%20', CUTTZ_CORE_SKINS_URL . '/' . basename( $customization ) . '/style.scss' );
			}
			if ( file_exists( $customization . '/functions.php' ) ) {
				$all_customizations[$id]['functions'] = $customization . '/functions.php';
			}

			foreach ( $extns as $extn ) {
				if ( file_exists( $customization . "/screenshot.$extn" ) ) {
					$all_customizations[$id]['screenshot'] = str_replace( ' ', '%20', CUTTZ_CORE_SKINS_URL . '/' . basename( $customization ) . "/screenshot.$extn" );
				}
			}
		}
	}
	
	if ( is_array( $user_customizations ) ) {
		foreach ( $user_customizations as $customization ) {
			if ( !file_exists( $customization . '/functions.php' ) && !file_exists( $customization . '/style.css' ) && !file_exists( $customization . '/style.scss' ) ) {
				continue;
			}
			$name                            = preg_replace( '/[^A-Za-z0-9\-\s]/', '', basename( $customization ) );
			$name                            = str_replace( '-', ' ', $name );
			$name                            = ucwords( strtolower( $name ) ) . ' (User)';
			$id                              = cuttz_ws( basename( $customization ) );
			$all_customizations[$id]         = array(
				'name' => $name
			);
			$all_customizations[$id]['type'] = 'user';
			$all_customizations[$id]['dir']  = str_replace( ' ', '%20', $customization );
			$all_customizations[$id]['url']  = str_replace( ' ', '%20', CUTTZ_USER_SKINS_URL . '/' . basename( $customization ) );
			if ( file_exists( $customization . '/autogenerated.css' ) ) {
				$all_customizations[$id]['style'] = str_replace( ' ', '%20', CUTTZ_USER_SKINS_URL . '/' . basename( $customization ) . '/autogenerated.css' );
			} //this can be buggy if a user copies a core customization and removes the style etc.
			else {
				unset( $all_customizations[$id]['style'] );
			}
			if ( file_exists( $customization . '/style.scss' ) ) {
				$all_customizations[$id]['sass'] = str_replace( ' ', '%20', CUTTZ_USER_SKINS_URL . '/' . basename( $customization ) . '/style.scss' );
			} //this can be buggy if a user copies a core customization and removes the style etc.
			else {
				unset( $all_customizations[$id]['sass'] );
			}
			if ( file_exists( $customization . '/functions.php' ) ) {
				$all_customizations[$id]['functions'] = $customization . '/functions.php';
			} //this can be buggy if a user copies a core customization and removes the style etc.
			else {
				unset( $all_customizations[$id]['functions'] );
			}
			foreach ( $extns as $extn ) {
				if ( file_exists( $customization . "/screenshot.$extn" ) ) {
					$all_customizations[$id]['screenshot'] = str_replace( ' ', '%20', CUTTZ_USER_SKINS_URL . '/customizations/' . basename( $customization ) . "/screenshot.$extn" );
				}
			}
		}
	}

	$skins;
	if ( !is_array( $all_customizations ) ) {
		$skins = FALSE;
	} else {
		$skins = $all_customizations;
	}
	return apply_filters( 'cuttz_skins', $skins );
}

/**
 * Enqueues settings.css, debug.css (if current user can manage options, google web fonts)
 * @return none
 * @since 1.0
 */
function cuttz_settings_css() {
	
	if ( @cuttz_get_res( 'file', 'settingscss' ) ) {
		wp_register_style( 'cuttz-settings-style', cuttz_get_res( 'fileurl', 'settingscss' ), array(), is_user_logged_in() ? microtime() : null, 'all' );
	}

	if ( is_admin() || current_user_can( 'manage_options' ) ) {
		wp_enqueue_style( 'cuttz-debug-style', cuttz_get_res( 'dirurl' ) . 'debug.css', array(), microtime(), 'all' );
	} else {
		wp_enqueue_style( 'cuttz-settings-style' );
	}

	$cuttz_fonts_url = genesis_get_option( 'cuttz-web-fonts', cuttz_get_skin_page_id(), false );
	if ( !empty( $cuttz_fonts_url ) ) {
		$protocol = is_ssl() ? 'https' : 'http';
		wp_enqueue_style( 'cuttz-fonts', $protocol . '://fonts.googleapis.com/css?family=' . $cuttz_fonts_url, array(), null, 'all' );
	}

}

add_filter( 'genesis_export_options', 'cuttz_export_options' );

/**
 * Inserts Cuttz options for all skins plus admin settings in the Genesis import/export settings page
 * @param type $options 
 * @return type
 * @since 1.0
 */
function cuttz_export_options( $options ) {
	global $_cuttz_admin_skin_settings;
	$cuttz_skins = cuttz_customization_aggregator();
	if ( is_array( $cuttz_skins ) ) {
		foreach ( $cuttz_skins as $skin => $info ) {
			$settings                                      = get_option( CHILD_SETTINGS_FIELD . '-' . $skin );
			$options[CHILD_SETTINGS_FIELD . '-' . $skin] = array(
				'label' => sprintf( __( 'Cuttz Skin Settings &mdash; %s', 'cuttz-framework' ), $info['name'] ),
				'settings-field' => CHILD_SETTINGS_FIELD . '-' . $skin
			);
		}
	}
	$options['cuttz'] = array(
		'label' => CHILD_THEME_NAME . __( ' Admin Settings', 'cuttz-framework' ),
		'settings-field' => CHILD_SETTINGS_FIELD_EXTRAS
	);
	return $options;
}

/**
 * Default admin settings for Cuttz
 * @return array
 * @since 1.0
 */
function cuttz_admin_defaults() {
	$defaults                                     = array();
	$defaults['settings-version']                 = 'false';
	$defaults['gfonts-api-key']                   = '';
	$defaults['skin']                             = 'vanilla';
	$defaults['footer-widgets-count']             = 3;
	$defaults['footer-widgets']                   = 1;
	$defaults['widgets_before_header_front']      = 1; //above header widget area
	$defaults['widgets_before_header_posts_page'] = 1;
	$defaults['widgets_before_header_home']       = 1;
	$defaults['widgets_before_header_post']       = 1;
	$defaults['widgets_before_header_page']       = 1;
	$defaults['widgets_before_header_archives']   = 1;
	$defaults['widgets_before_header_404']        = 1;
	$defaults['widgets_after_header_front']       = 1; //after header widget area
	$defaults['widgets_after_header_posts_page']  = 1;
	$defaults['widgets_after_header_home']        = 1;
	$defaults['widgets_after_header_post']        = 1;
	$defaults['widgets_after_header_page']        = 1;
	$defaults['widgets_after_header_archives']    = 1;
	$defaults['widgets_after_header_404']         = 1;
	$defaults['widgets_above_footer_front']       = 1; //above footer widget area
	$defaults['widgets_above_footer_posts_page']  = 1;
	$defaults['widgets_above_footer_home']        = 1;
	$defaults['widgets_above_footer_post']        = 1;
	$defaults['widgets_above_footer_page']        = 1;
	$defaults['widgets_above_footer_archives']    = 1;
	$defaults['widgets_above_footer_404']         = 1;
	$defaults['mlp_hide_breadcrumbs']             = 1; //Mobile template defaults
	$defaults['mlp_hide_widgets_above_header']    = 1;
	$defaults['mlp_hide_widgets_below_header']    = 1;
	$defaults['mlp_hide_widgets_above_footer']    = 1;
	$defaults['mlp_hide_sidebars']                = 0;
	$defaults['mlp_hide_fwidgets']                = 0;
	$defaults['widget-default-content-enabled']   = 1; //Debug options
	$defaults['custom-functions-enabled']         = 1; //Debug options
	$defaults['current-skin-functions-enabled'] = 1;
	$defaults['custom-style-enabled']             = 1;
	$defaults['current-skin-style-enabled']     = 1;

	return apply_filters( 'cuttz_admin_defaults', $defaults );
}


/**
 * Default skin settings for all Skins
 * @return array
 * @since 1.0
 * ***NOTE: All font-family settings must have the string "font-family" in the setting name. Cuttz uses it to detect & validate font-family related settings, detect web fonts and enqueue them
 */

function cuttz_skin_defaults() {
	$defaults = array();
	$defaults['skin-version']                 				= 'false';
	$defaults['layout']										= 'fullwidth';
	if ( function_exists( 'bbpress' ) ) {
		$defaults['bbpress-layout'] = 'default';
	}

	$defaults['col-spacing']                                = '40';
	$defaults['column-content-1col']                        = '960';
	$defaults['column-content-2col']                        = '670';
	$defaults['sidebar-one-2col']                           = '250';
	$defaults['column-content-3col']                        = '480';
	$defaults['sidebar-one-3col']                           = '200';
	$defaults['sidebar-two-3col']                           = '200';
	
	$defaults['site-background-color']                      = '#ffffff';
	$defaults['page-background-color']                      = '#ffffff';
	
	$defaults['body-font-family']                           = 'roboto';
	$defaults['body-font-weight']                           = '300';
	$defaults['body-font-size']                             = '15';
	$defaults['primary-text-color']                         = '#333333';
	$defaults['primary-link-color']                         = '#2361a1';
	$defaults['primary-link-hover-color']                   = '#1c4d80';
	$defaults['form-font-family']                           = $defaults['body-font-family'];
	$defaults['form-text-color']                            = '#666666';
	$defaults['form-font-size']                             = '14';
	
	$defaults['site-title-font-color']                      = '#333333';
	$defaults['site-title-font-size']                       = '72';
	$defaults['site-title-font-family']                     = 'italianno';
	$defaults['site-title-font-weight']                     = 'regular';
	$defaults['site-description-font-color']                = '#666666';
	$defaults['site-description-font-size']                 = '14';
	$defaults['site-description-font-family']               = 'roboto';
	$defaults['site-description-font-weight']               = '300';
	
	$defaults['nav-menu-font-family']                       = 'roboto';
	$defaults['nav-menu-font-weight']                       = '300';
	$defaults['nav-menu-font-size']                         = '15';
	$defaults['nav-menu-link-text-color']                   = '#555555';
	$defaults['nav-menu-link-text-hover-color']             = '#333333';
	$defaults['nav-menu-current-link-text-color']           = '#333333';
	$defaults['nav-menu-current-parent-link-text-color']    = '#333333';
	$defaults['nav-menu-link-bg-color']                     = '#ffffff';
	$defaults['nav-menu-hover-bg-color']                    = '#f4f4f4';
	$defaults['nav-menu-current-bg-color']                  = '#f4f4f4';
	$defaults['nav-menu-current-parent-bg-color']           = '#f4f4f4';
	$defaults['nav-menu-border-width']                      = '1';
	$defaults['nav-menu-border-color']                      = '#dddddd';
	$defaults['nav-menu-submenu-width']                     = '200';
	
	$defaults['subnav-menu-font-family']                    = 'roboto';
	$defaults['subnav-menu-font-weight']                    = '300';
	$defaults['subnav-menu-font-size']                      = '13';
	$defaults['subnav-menu-link-text-color']                = '#555555';
	$defaults['subnav-menu-link-text-hover-color']          = '#333333';
	$defaults['subnav-menu-current-link-text-color']        = '#333333';
	$defaults['subnav-menu-current-parent-link-text-color'] = '#333333';
	$defaults['subnav-menu-link-bg-color']                  = '#f4f4f4';
	$defaults['subnav-menu-hover-bg-color']                 = '#e8e8e8';
	$defaults['subnav-menu-current-bg-color']               = '#e8e8e8';
	$defaults['subnav-menu-current-parent-bg-color']        = '#e8e8e8';
	$defaults['subnav-menu-border-width']                   = '0';
	$defaults['subnav-menu-border-color']                   = '#dddddd';
	$defaults['subnav-menu-submenu-width']                  = '200';
	
	$defaults['headline-font-family']                       = 'roboto_condensed';
	$defaults['headline-font-weight']                       = 'regular';
	$defaults['headline-font-color']                        = '#333333';
	$defaults['headline-font-size']                         = '28';
	$defaults['headline-subhead-font-color']                = '#333333';
	$defaults['headline-subhead-font-family']               = 'roboto_condensed';
	$defaults['headline-subhead-font-weight']               = 'regular';
	
	$defaults['byline-font-family']                         = 'roboto';
	$defaults['byline-font-weight']                         = '300';
	$defaults['byline-font-color']                          = '#808080';
	$defaults['byline-font-size']                           = '12';
	
	$defaults['sidebar-heading-font-family']                = 'roboto_condensed';
	$defaults['sidebar-heading-font-weight']                = 'regular';
	$defaults['sidebar-heading-font-size']                  = '18';
	$defaults['sidebar-heading-font-color']                 = '#333333';
	$defaults['sidebar-font-family']                        = 'roboto';
	$defaults['sidebar-font-weight']                        = '300';
	$defaults['sidebar-font-color']                         = '#333333';
	$defaults['sidebar-font-size']                          = '15';
	
	$defaults['footer-widgets-heading-font-family']         = 'roboto_condensed';
	$defaults['footer-widgets-heading-font-weight']         = 'regular';
	$defaults['footer-widgets-heading-font-size']           = '18';
	$defaults['footer-widgets-heading-font-color']          = '#333333';
	$defaults['footer-widgets-font-family']                 = 'roboto';
	$defaults['footer-widgets-font-weight']                 = '300';
	$defaults['footer-widgets-font-color']                  = '#333333';
	$defaults['footer-widgets-font-size']                   = '15';
	
	$defaults['footer-font-family']                         = 'roboto';
	$defaults['footer-font-weight']                         = 'regular';
	$defaults['footer-font-color']                          = '#888888';
	$defaults['footer-font-size']                           = '13';
	$defaults['cuttz-web-fonts']							= 'Roboto:300|Italianno:regular|Roboto|Italianno:regular|Roboto:300|Roboto+Condensed:regular|Roboto+Condensed:regular|Roboto:300|Roboto:300|Roboto:300|Roboto:300|Roboto+Condensed:regular|Roboto:300|Roboto+Condensed:regular|Roboto:regular';

	$defaults = apply_filters( 'cuttz_skin_defaults', $defaults );

	return $defaults;
}

/**
 * Defines global design variables. 
 * Todo: Not sure if we currently use them consistently.
 * @return none
 * @since 1.0
 */

function cuttz_global_vars() {
	$all_customizations = cuttz_customization_aggregator();
	$customization      = genesis_get_option( 'skin', CHILD_SETTINGS_FIELD_EXTRAS, false );
	if ( empty( $customization ) ) {
		define( 'SKIN', false );
		return;
	} else {
		define( 'SKIN', $customization );
	}
	if ( is_array( $all_customizations ) && array_key_exists( $customization, $all_customizations ) ) {
		$customization = $all_customizations[$customization];
		define( 'SKIN_DIR', $customization['dir'] );
		define( 'SKIN_URL', $customization['url'] );
		if ( is_array( $customization ) && array_key_exists( 'functions', $customization ) ) {
			define( 'SKIN_FUNCTIONS', $customization['functions'] );
		}
		if ( is_array( $customization ) && array_key_exists( 'style', $customization ) ) {
			define( 'SKIN_STYLE', $customization['style'] );
		}
		if ( is_array( $customization ) && array_key_exists( 'sass', $customization ) ) {
			define( 'SKIN_SASS', $customization['sass'] );
		}
		if ( is_array( $customization ) && array_key_exists( 'screenshot', $customization ) ) {
			define( 'SKIN_SCREENSHOT', $customization['screenshot'] );
		}
	}

	global $cuttz_admin_defaults;
	$cuttz_admin_defaults = cuttz_admin_defaults();

	global $cuttz_skin_defaults;
	$cuttz_skin_defaults = cuttz_skin_defaults();

}

/**
 * Outputs the Cuttz footer menu.
 * @return none
 * @since 1.0
 */
function cuttz_do_nav_footer() {
	if ( !genesis_nav_menu_supported( 'footer_menu' ) ) {
		return;
	}
	if ( has_nav_menu( 'footer_menu' ) ) {
		$class = 'menu cuttz-menu-footer';
		if ( genesis_superfish_enabled() ) {
			$class .= ' js-superfish';
		}
		$args = array(
			'theme_location' => 'footer_menu',
			'container' => '',
			'menu_class' => $class,
			'depth' => 1, // Allows only parent items to be included in the menu
			'echo' => 0
		);
		$nav  = wp_nav_menu( $args );
		if ( !$nav ) {
			return;
		}
		$nav_markup_open  = genesis_markup( array(
				'html5' => '<nav %s>',
				'xhtml' => '<div id="cuttz-nav-footer menu">',
				'context' => 'cuttz-nav-footer',
				'echo' => false
			) );
		$nav_markup_close = genesis_html5() ? '</nav>' : '</div>';
		$nav_output       = $nav_markup_open . $nav . $nav_markup_close;
		echo apply_filters( 'cuttz_do_nav_footer', $nav_output, $nav, $args );
	}
}

/**
 * Wraps the footer output in a div with the classname creds for styling?
 * @param string $output 
 * @param string $backtotop 
 * @param string $creds 
 * @return string
 * @since 1.0
 */
function cuttz_footer_output( $output, $backtotop, $creds ) {
	return '<div class="creds">' . $output . '</div>';
}

/**
 * Modifies the Genesis attribute anchor text slightly for better readability.
 * @param string $output 
 * @param array? $atts 
 * @return string
 * @since 1.0
 */
function cuttz_genesis_link_output( $output, $atts ) {
	$output = str_replace( "Genesis Framework</a>", "Genesis</a>", $output );
	return $output;
}

/**
 * Inserts a copyright notice and site ownership in the footer.
 * @param string $creds_text 
 * @return string
 * @since 1.0
 */
function cuttz_footer_creds( $creds_text ) {
	$cuttz_footer_creds = __( 'Copyright', 'cuttz-framework' ) . ' &copy; ' . date( 'Y' ) . ' &mdash; <a title="' . get_bloginfo( 'name' ) . '" href="' . get_site_url() . '">' . get_bloginfo( 'name' ) . '</a>&nbsp;&bull;&nbsp;' . __( 'All Rights Reserved', 'cuttz-framework' ) . '&nbsp;&bull;&nbsp;' . __( 'Powered by', 'cuttz-framework' ) . '&nbsp;' . do_shortcode( '[footer_childtheme_link before=""]' ) . '&nbsp;on&nbsp;' . do_shortcode( '[footer_genesis_link url="https://binaryturf.com/genesis"]' ) . '.';
	
	return apply_filters( 'cuttz_footer_creds', $cuttz_footer_creds );
}


/**
 * Inserts certain body classes for styling purposes
 * @param array $classes 
 * @return array
 * @since 1.0
 */
function cuttz_body_classes( $classes ) {
	$classes[]      = genesis_get_option( 'layout', cuttz_get_skin_page_id(), false );
	$classes[]      = genesis_get_option( 'skin', CHILD_SETTINGS_FIELD_EXTRAS, false );
	$footer_widgets = genesis_get_option( 'footer-widgets-count', CHILD_SETTINGS_FIELD_EXTRAS, false );
	$classes[]      = 'footer-' . $footer_widgets;
	$classes[]      = 'cuttz';
	if ( cuttz_is_mobile() ) {
		$classes[] = 'cuttz-mobile-viewport';
	}

	return $classes;
}

/**
 * Modify the active body classes for layout styles depending on per page layout set by the user
 */
function cuttz_set_page_custom_layout( $classes ) {
	global $post;
	$selected_page_layout = get_post_meta( $post->ID, '_cuttz_page_layout', true );
	$active_site_layout = genesis_get_option( 'layout', cuttz_get_skin_page_id(), false );
	
	if( empty( $selected_page_layout ) )
		return $classes;
	
	// Unset the current active layout class
	if( !empty( $active_site_layout ) ) {
		foreach( $classes as $index => $value ) {
			if( $value == $active_site_layout )
				unset( $classes[$index] );
		}
	}

	// Set the user selected layout class
	$classes[] = $selected_page_layout;
	
	return $classes;
}


/**
 * Inserts certain body classes to Cuttz Admin pages for styling purposes
 * @param array $classes 
 * @return array
 * @since 1.0
 */
function cuttz_admin_body_classes( $classes ) {

	$screen    = get_current_screen();
	$screen_id = $screen->base;

	$cuttz_admin_page  = 'genesis_page_' . CHILD_SETTINGS_FIELD_EXTRAS;
	$cuttz_skin_page = 'genesis_page_' . cuttz_get_skin_page_id();

	if ( $screen_id == $cuttz_admin_page || $screen_id == $cuttz_skin_page ) {
		$classes .= 'cuttz-framework';
	}

	return $classes;

}

/**
 * Enqueues jQuery
 * @return type
 * @since 1.0
 */
function cuttz_enqueue_jquery() {
	wp_enqueue_script( 'jquery' );
}


/**
 * Enqueues the cuttz scripts js
 * @return none
 * @since 1.0
 */
function cuttz_scripts() {
	wp_enqueue_script( 'cuttz-scripts', get_stylesheet_directory_uri() . '/lib/js/cuttz-scripts.js', array(
			'jquery'
		), '1.0.0', true );
}


/**
 * Enqueues the responsive menu js
 * @return none
 * @since 1.0
 */
function cuttz_res_menu_output() {
	wp_enqueue_script( 'cuttz-res-menu-output', get_stylesheet_directory_uri() . '/lib/js/responsive-menu.js', array(
			'jquery'
		), '1.0.0', true );
}


/**
 * Enqueues the retina js
 * @return none
 * @since 1.0
 */
function cuttz_retina_script() {
	wp_enqueue_script( 'cuttz-retina-script', get_stylesheet_directory_uri() . '/lib/js/retina.min.js', array(
			'jquery'
		), '1.0.0', true );
}


/**
 * Inserts the schema to the frontend
 * @return none
 * @since 1.0
 */
function cuttz_attributes_node( $attributes ) {
	global $post;
	$saved_schema            = get_post_meta( $post->ID, '_cuttz_schema', 1 );
	$schema                  = cuttz_get_schema( $saved_schema );
	$attributes['itemtype']  = $schema['itemtype'];
	$attributes['itemscope'] = 'itemscope';
	return $attributes;
}

/**
 * Inserts a read more link if excerpts are enabled on archives
 * @return none
 * @since 1.0
 */
function show_read_more_on_excerpt() {
	if ( is_singular() || ( function_exists( 'is_bbPress' ) && is_bbPress() ) ) {
		return;
	}
	if ( 'excerpts' == genesis_get_option( 'content_archive' ) || has_excerpt() ) {
		echo '<p class="more-link-excerpt"><a href="' . get_permalink() . '" class="more-link">' . __( 'Read more', 'cuttz-framework' ) . '&hellip;</a></p>';
	}
}

/**
 * Helper function to modify the pagination text to our taste.
 * @param string $text 
 * @return string
 * @since 1.0
 */
function cuttz_previous_page_link( $text ) {
	return '&laquo; ' . __( 'Newer', 'cuttz-framework' );
}

/**
 * Helper function to modify the pagination text to our taste.
 * @param string $text 
 * @return string
 * @since 1.0
 */
function cuttz_next_page_link( $text ) {
	return __( 'Older', 'cuttz-framework' ) . ' &raquo; ';
}

/**
 * Linkifies the postdate to the permalink
 * @param string $date 
 * @return string
 * @since 1.0
 */
function cuttz_post_date_shortcode( $date ) {
	return '<a href="' . get_permalink() . '" title="Permalink">' . $date . '</a>';
}

/**
 * Inserts the .sticky post class for the sticky posts.
 * @param array $classes 
 * @return array
 * @since 1.0
 */
function cuttz_post_classes( $classes ) {
	global $post;
	if ( is_sticky( $post->ID ) && !is_singular() ) {
		$classes[] = "sticky";
	}
	return $classes;
}

function cuttz_add_inpost_layout_box() {
	if ( !current_theme_supports( 'genesis-inpost-layouts' ) )
		return;
	foreach ( (array) get_post_types( array(
				'public' => true
			) ) as $type ) {
		if ( post_type_supports( $type, 'genesis-layouts' ) )
			add_meta_box( 'genesis_inpost_layout_box', __( 'Layout Settings', 'cuttz-framework' ), 'genesis_inpost_layout_box', $type, 'normal', 'default' );
	}
}

/**
 * Disables theme update check for Cuttz from the WP repo
 * @param array $r 
 * @param string $url 
 * @return array
 * @since 1.0
 */
function cuttz_dont_update_theme( $r, $url ) {
	if ( 0 !== strpos( $url, 'http://api.wordpress.org/themes/update-check' ) )
		return $r;
	$themes = unserialize( $r['body']['themes'] );
	unset( $themes[get_option( 'template' )] );
	unset( $themes[get_option( 'stylesheet' )] );
	$r['body']['themes'] = serialize( $themes );
	return $r;
}

/**
 * Enqueues the master style.css
 * @return none
 * @since 1.0
 */
function cuttz_user_css() {
	if ( !genesis_get_option( 'custom-style-enabled', CHILD_SETTINGS_FIELD_EXTRAS, false ) ) {
		return;
	}
	$usercss = cuttz_get_res( 'file', 'usercss' );
	if ( @file_exists( $usercss ) ) {
		wp_register_style( 'cuttz-user-style', cuttz_get_res( 'fileurl', 'usercss' ), array(), is_user_logged_in() ? microtime() : null, 'all' );
	}
	if ( !is_admin() ) {
		wp_enqueue_style( 'cuttz-user-style' );
	}
}


/**
 * Enqueues the skin specific css
 * @return none
 * @since 1.0
 */
function cuttz_customizations_css() {
	if ( !genesis_get_option( 'current-skin-style-enabled', CHILD_SETTINGS_FIELD_EXTRAS, false ) ) {
		return;
	}
	$customization      = '';
	$all_customizations = cuttz_customization_aggregator();
	$customization      = genesis_get_option( 'skin', CHILD_SETTINGS_FIELD_EXTRAS, false );
	if ( is_array( $all_customizations ) && array_key_exists( $customization, $all_customizations ) ) {
		$current_customization = $all_customizations[$customization];
		if ( is_array( $current_customization ) && array_key_exists( 'style', $current_customization ) ) {
			wp_enqueue_style( 'cuttz-customization-style', $current_customization['style'] );
		}
	}
}

/**
 * Returns the Logo/headerimage path or hooks the entire header CSS to front-end.
 * @param bool $return 
 * @return none/string
 * @since 1.0
 */
function cuttz_logo( $return = true ) {
	$cuttz_logo;
	$cuttz_logo_path = '';
	$logo_types       = cuttz_logo_types();
	$logo_dest        = cuttz_get_res( 'dir' ) . 'img/logo.';
	foreach ( $logo_types as $ext ) {
		if ( file_exists( $logo_dest . $ext ) ) {
			$cuttz_logo      = cuttz_get_res( 'dirurl' ) . 'img/logo.' . $ext;
			$cuttz_logo_path = $logo_dest . $ext;
		}
	}
	if ( !isset( $cuttz_logo ) ) {
		$cuttz_logo = CHILD_URL . '/images/logo.svg';
	}

	if ( $return ) {
		return $cuttz_logo;
	}

	if ( file_exists( $cuttz_logo_path ) ) {
		$logo_info       = getimagesize( $cuttz_logo );
		$logo_height     = 'min-height:' . ( .5 * $logo_info[1] ) . 'px';
		$cuttz_logo_css = '.cuttz.header-image .site-header .wrap {' . $logo_height . ';background-image :url(' . $cuttz_logo . '); background-repeat: no-repeat; background-position: left center; background-size: contain;}' . '.header-image .site-title a{' . $logo_height . ';}';
		echo '<style type="text/css">' . $cuttz_logo_css . '</style>';
	}
}

/**
 * Beautifully formated var_dump for developers for troubleshooting purposes. Makes life easy by showing the variable/object/array's gory details.
 * @param array/object/variable/etc $text 
 * @param bool $echo 
 * @return none || string
 * @since 1.0
 */
function llog( $text, $echo = true ) {
	if ( $echo ) {
		echo '<pre>';
		var_dump( $text );
		echo '</pre>';
	} else {
		ob_start();
		var_dump( $text );
		$result = ob_get_clean();
		return '<pre>' . $result . '</pre>';
	}
}


/**
 * Beautifully formatted var_dump for developers for troubleshooting purposes. Makes life easy by WRITING the variable/object/array's gory details into ABSPATH . "cuttz-log.txt"
 * @param array/object/variable/etc $text 
 * @return none
 * @since 1.0
 */
function llogfile( $text = 'hello' ) {
	$out = llog( $text, false );
	file_put_contents( ABSPATH . "cuttz-log.txt", $out . PHP_EOL, FILE_APPEND );
}


/**
 * Disable the activation redirection when Cuttz is in deployment mode.
 * @return none
 * @since 1.0
 */
function cuttz_redir_settings() {
	if ( current_theme_supports( 'cuttz-deploy' ) || current_theme_supports( 'cuttz-admin-deploy' ) )
		return;

	if ( isset( $_GET['activated'] ) ) {
		do_action( 'cuttz_update', 'installed' );
	}
}

/**
 * Helper function that forces full-width layout
 * @param string $layout 
 * @return string
 * @since 1.0
 */
function cuttz_force_full_width_layout( $layout ) {
	$layout = 'full-width-content';
	return $layout;
}


/**
 * Helper function that hides the breadcrumbs when hidden in the options panel
 * @return bool
 * @since 1.0
 */
function cuttz_hide_breadcrumbs() {
	return false;
}


/**
 * Adds 'cuttz-no-bcrumb' class to <body> so that the breadcrumbs can be visually hidden
 * Breadcrumbs being important for SEO, should stay in the page markup, hence we'd disable them visually on the site if user chooses to do so
 * @param array $classes
 * @return array $classes
 * @since 1.1.1
 */
function cuttz_seo_hide_breadcrumbs( $classes ) {
	$no_bcrumb_class = 'cuttz-no-bcrumb';
	$classes[] =  esc_attr( sanitize_html_class( $no_bcrumb_class ) );
	
	return $classes;
}


/**
 * Inserts the hide-title class into the post that enables us to hide post title via CSS
 * @param array $classes 
 * @return array
 * @since 1.0
 */
function cuttz_hide_title_class( $classes ) {
	if ( in_the_loop() ) {
		$new_class = 'hide-title';
		$classes[] = esc_attr( sanitize_html_class( $new_class ) );
	}
	return $classes;
}


/**
 * Replaces bozo brackets with attitude brackets in the post edit link on the front-end
 * @param string $link 
 * @return string
 * @since 1.0
 */
function cuttz_post_edit_link( $link ) {
	$link = str_replace( '(', '[', $link );
	$link = str_replace( ')', ']', $link );
	return $link;
}

/**
 * Helper function that converts any string into a websafe string
 * @param string $str 
 * @return string
 */
function cuttz_ws( $str ) {
	return preg_replace( "/[\/_| -]+/u", '-', strtolower( trim( preg_replace( "/[^a-zA-Z0-9\/_| -]/u", '', $str ), '-' ) ) );
}

/**
 * Removes the Cuttz Admin Menus when Cuttz framework is in deployment mode
 * @return none
 * @since 1.0
 */
function cuttz_menus() {
	if ( current_theme_supports( 'cuttz-deploy' ) ) {
		remove_submenu_page( 'genesis', CHILD_SETTINGS_FIELD_EXTRAS );
		remove_submenu_page( 'genesis', CHILD_SETTINGS_FIELD_BRANDING );
		remove_submenu_page( 'genesis', cuttz_get_skin_page_id() );
	}
	if ( current_theme_supports( 'cuttz-admin-deploy' ) ) {
		remove_submenu_page( 'genesis', CHILD_SETTINGS_FIELD_EXTRAS );
	}
	if ( current_theme_supports( 'cuttz-branding-deploy' ) ) {
		remove_submenu_page( 'genesis', CHILD_SETTINGS_FIELD_BRANDING );
	}
	if ( current_theme_supports( 'cuttz-skin-deploy' ) ) {
		remove_submenu_page( 'genesis', cuttz_get_skin_page_id() );
	}
}

/**
 * Changes Site Name to H2 (Genesis does an H1 by default). Bozo?
 * @param type $title 
 * @param type $inside 
 * @param type $wrap 
 * @return type
 * @since 1.0
 */
function cuttz_title( $title, $inside, $wrap ) {
	$tag   = is_home() && 'title' === genesis_get_seo_option( 'home_h1_on' ) ? 'h1' : 'p';
	$tag   = genesis_html5() && genesis_get_seo_option( 'semantic_headings' ) ? 'h2' : $tag;
	$title = preg_replace( "/<$wrap\s(.+?)>(.+?)<\/$wrap>/is", "<$tag $1>$2</$tag>", $title );
	return $title;
}

/**
 * Changes Site Description to H1 (Genesis does an H2 by default). Bozo?
 * @param type $title 
 * @param type $inside 
 * @param type $wrap 
 * @return type
 * @since 1.0
 */
function cuttz_desc( $description, $inside, $wrap ) {
	$tag         = is_home() && 'description' === genesis_get_seo_option( 'home_h1_on' ) ? 'h1' : 'p';
	$tag         = genesis_html5() && genesis_get_seo_option( 'semantic_headings' ) ? 'h1' : $tag;
	$description = preg_replace( "/<$wrap\s(.+?)>(.+?)<\/$wrap>/is", "<$tag $1>$2</$tag>", $description );
	return $description;
}


/**
 * Outputs Cuttz widget area before header
 * @return none
 * @since 1.0
 */
function cuttz_sidebar_before_header() {

	$show = ( ( ( 'posts' === get_option( 'show_on_front' ) && is_home() ) && genesis_get_option( 'widgets_before_header_home', CHILD_SETTINGS_FIELD_EXTRAS, false ) ) || ( ( 'page' === get_option( 'show_on_front' ) && is_front_page() ) && genesis_get_option( 'widgets_before_header_front', CHILD_SETTINGS_FIELD_EXTRAS, false ) ) || ( ( 'page' === get_option( 'show_on_front' ) && is_home() ) && genesis_get_option( 'widgets_before_header_posts_page', CHILD_SETTINGS_FIELD_EXTRAS, false ) ) || ( is_single() && genesis_get_option( 'widgets_before_header_post', CHILD_SETTINGS_FIELD_EXTRAS, false ) ) || ( ( is_page() && !is_front_page() ) && genesis_get_option( 'widgets_before_header_page', CHILD_SETTINGS_FIELD_EXTRAS, false ) ) || ( ( is_archive() || is_search() ) && genesis_get_option( 'widgets_before_header_archives', CHILD_SETTINGS_FIELD_EXTRAS, false ) ) || ( is_404() && genesis_get_option( 'widgets_before_header_404', CHILD_SETTINGS_FIELD_EXTRAS, false ) ) );
	$show = apply_filters( 'show_widgets_before_header', $show );
	if ( $show ) {
		if ( is_active_sidebar( 'before-header' ) ) {
			echo '<div class="cuttz-sb-before-header"><div class="wrap cuttz-sb-wrap cuttz-sb-before-header-wrap">';
			genesis_widget_area( 'before-header' );
			echo '</div></div>';
		} else {
			if ( current_user_can( 'edit_theme_options' ) ) {
				$cuttz_show_default_widget_content = apply_filters( 'widget_default_content_enabled', genesis_get_option( 'widget-default-content-enabled', CHILD_SETTINGS_FIELD_EXTRAS, false ) );
				if ( $cuttz_show_default_widget_content ) {
					echo '<div class="cuttz-sb-before-header"><div class="wrap cuttz-sb-wrap cuttz-sb-before-header-wrap">';
					genesis_default_widget_area_content( __( 'Before Header Widget Area', 'cuttz-framework' ) );
					echo '</div></div>';
				}
			}
		}
	}
}

/**
 * Outputs Cuttz widget area after header
 * @return none
 * @since 1.0
 */
function cuttz_sidebar_after_header() {
	$show = ( ( ( 'posts' === get_option( 'show_on_front' ) && is_home() ) && genesis_get_option( 'widgets_after_header_home', CHILD_SETTINGS_FIELD_EXTRAS, false ) ) || ( ( 'page' === get_option( 'show_on_front' ) && is_front_page() ) && genesis_get_option( 'widgets_after_header_front', CHILD_SETTINGS_FIELD_EXTRAS, false ) ) || ( ( 'page' === get_option( 'show_on_front' ) && is_home() ) && genesis_get_option( 'widgets_after_header_posts_page', CHILD_SETTINGS_FIELD_EXTRAS, false ) ) || ( is_single() && genesis_get_option( 'widgets_after_header_post', CHILD_SETTINGS_FIELD_EXTRAS, false ) ) || ( ( is_page() && !is_front_page() ) && genesis_get_option( 'widgets_after_header_page', CHILD_SETTINGS_FIELD_EXTRAS, false ) ) || ( ( is_archive() || is_search() ) && genesis_get_option( 'widgets_after_header_archives', CHILD_SETTINGS_FIELD_EXTRAS, false ) ) || ( is_404() && genesis_get_option( 'widgets_after_header_404', CHILD_SETTINGS_FIELD_EXTRAS, false ) ) );

	$show = apply_filters( 'show_widgets_after_header', $show );

	if ( $show ) {
		if ( is_active_sidebar( 'after-header' ) ) {
			echo '<div class="cuttz-sb-after-header"><div class="wrap cuttz-sb-wrap cuttz-sb-after-header-wrap">';
			genesis_widget_area( 'after-header' );
			echo '</div></div>';
		} else {
			if ( current_user_can( 'edit_theme_options' ) ) {
				$cuttz_show_default_widget_content = apply_filters( 'widget-default-content-enabled', genesis_get_option( 'widget-default-content-enabled', CHILD_SETTINGS_FIELD_EXTRAS, false ) );
				if ( $cuttz_show_default_widget_content ) {
					echo '<div class="cuttz-sb-after-header"><div class="wrap cuttz-sb-wrap cuttz-sb-after-header-wrap">';
					genesis_default_widget_area_content( __( 'After Header Widget Area', 'cuttz-framework' ) );
					echo '</div></div>';
				}
			}
		}
	}
}


/**
 * Outputs Cuttz widget area above footer
 * @return none
 * @since 1.0
 */
function cuttz_sidebar_above_footer() {
	$show = ( ( ( 'posts' === get_option( 'show_on_front' ) && is_home() ) && genesis_get_option( 'widgets_above_footer_home', CHILD_SETTINGS_FIELD_EXTRAS, false ) ) || ( ( 'page' === get_option( 'show_on_front' ) && is_front_page() ) && genesis_get_option( 'widgets_above_footer_front', CHILD_SETTINGS_FIELD_EXTRAS, false ) ) || ( ( 'page' === get_option( 'show_on_front' ) && is_home() ) && genesis_get_option( 'widgets_above_footer_posts_page', CHILD_SETTINGS_FIELD_EXTRAS, false ) ) || ( is_single() && genesis_get_option( 'widgets_above_footer_post', CHILD_SETTINGS_FIELD_EXTRAS, false ) ) || ( ( is_page() && !is_front_page() ) && genesis_get_option( 'widgets_above_footer_page', CHILD_SETTINGS_FIELD_EXTRAS, false ) ) || ( ( is_archive() || is_search() ) && genesis_get_option( 'widgets_above_footer_archives', CHILD_SETTINGS_FIELD_EXTRAS, false ) ) || ( is_404() && genesis_get_option( 'widgets_above_footer_404', CHILD_SETTINGS_FIELD_EXTRAS, false ) ) );
	$show = apply_filters( 'show_widgets_above_footer', $show );
	if ( $show ) {
		if ( is_active_sidebar( 'above-footer' ) ) {
			echo '<div class="cuttz-sb-above-footer"><div class="wrap cuttz-sb-wrap cuttz-sb-above-footer-wrap">';
			genesis_widget_area( 'above-footer' );
			echo '</div></div>';
		} else {
			if ( current_user_can( 'edit_theme_options' ) ) {
				$cuttz_show_default_widget_content = apply_filters( 'widget-default-content-enabled', genesis_get_option( 'widget-default-content-enabled', CHILD_SETTINGS_FIELD_EXTRAS, false ) );
				if ( $cuttz_show_default_widget_content ) {
					echo '<div class="cuttz-sb-above-footer"><div class="wrap cuttz-sb-wrap cuttz-sb-above-footer-wrap">';
					genesis_default_widget_area_content( __( 'Above Footer Widget Area', 'cuttz-framework' ) );
					echo '</div></div>';
				}
			}
		}
	}
}

/**
 * Registers all the custom widget areas
 * @return none
 * @since 1.0
 */
function cuttz_register_sidebars() {
	genesis_register_widget_area( array(
			'name' => __( 'Before Header', 'cuttz-framework' ),
			'id' => 'before-header',
			'description' => __( 'These widgets will show up above the header.', 'cuttz-framework' )
		) );
	genesis_register_widget_area( array(
			'name' => __( 'After Header', 'cuttz-framework' ),
			'id' => 'after-header',
			'description' => __( 'These widgets will show up below the header.', 'cuttz-framework' )
		) );
	genesis_register_widget_area( array(
			'name' => __( 'Above Footer', 'cuttz-framework' ),
			'id' => 'above-footer',
			'description' => __( 'These widgets will show up above the footer or the footer widgets if they are enabled.', 'cuttz-framework' )
		) );
}

/**
 * Spaces in the nav HTML markup don't allow us to style the nav correctly using inline-block style. Removes such spaces.
 * @param type $markup 
 * @param type $args 
 * @return type
 * @since 1.0
 */
function cuttz_nav_trim( $markup, $args ) {
	return preg_replace( '~>\s+<~', '><', $markup );
}


add_filter( 'genesis_post_meta', 'cuttz_post_meta_filter' );

/**
 * Helper function to remove the extra markup before post categories and post tags
 * @param string $post_meta 
 * @return string
 * @since 1.0
 */
function cuttz_post_meta_filter( $post_meta ) {
	$post_meta = '[post_categories before=""] [post_tags before=""]';
	return $post_meta;
}


add_filter( 'genesis_toggles', 'cuttz_admin_toggle' );

/**
 * Add toggle ability to footer widgets option on Cuttz Admin screen. The footer widgets count option displays only if footer widgets are enabled
 * @param array $toggles 
 * @return array
 * @since 1.0
 */
function cuttz_admin_toggle( $toggles ) {
	$toggles['footer-widgets'] = array(
		'#cuttz-framework-admin\\[footer-widgets\\]',
		'#fwidget-count',
		'1'
	);
	return $toggles;
}


/**
 * Helper function that can be called to check if we are on a mobile viewport
 * @return bool
 * @since 1.0
 */
function cuttz_is_mobile() {
	return apply_filters( 'cuttz_is_mobile', wp_is_mobile() );
}


/** Add theme support for Genesis Footer Widgets dynamically. **/
$footer_widgets      = genesis_get_option( 'footer-widgets', CHILD_SETTINGS_FIELD_EXTRAS, false );
$footer_widget_count = genesis_get_option( 'footer-widgets-count', CHILD_SETTINGS_FIELD_EXTRAS );
if ( $footer_widgets ) {
	add_theme_support( 'genesis-footer-widgets', $footer_widget_count );
}



/**
 * Callback for Cuttz Help area on Cuttz Settings and Cuttz Design screen
 * @return none
 * @since 1.0
 */
function cuttz_admin_sidebar() {
	
	$disable = apply_filters( 'cuttz_hide_admin_sb', false );
	if ( $disable !== false ) {
		return $disable;
	}

	?>
		<!-- Cuttz Help Area -->
		
		<div class="cuttz-sidebar">
			<div class="cuttz-help-area section">
			<h3><?php _e( 'Cuttz Framework Help &amp; Support', 'cuttz-framework' ); ?></h3>
			<div class="cuttz-postbox-wrapper">
			<ul>
			<!-- Documentation to get started with Cuttz -->
			<li><span class="dashicons dashicons-lightbulb"></span><a class="cuttz-admin-help" href="https://www.binaryturf.com/?p=17953"><?php _e( 'Getting Started', 'cuttz-framework' ); ?></a></li>
			
			<!-- Documentation to help with usage -->
			<li><span class="dashicons dashicons-editor-help"></span><a class="cuttz-admin-help" href="https://www.binaryturf.com/?p=17950"><?php _e( 'Docs &amp; References', 'cuttz-framework' ); ?></a></li>

			<!-- Report a bug -->
			<li><span class="dashicons dashicons-flag"></span><a class="cuttz-admin-help" href="https://www.binaryturf.com/?p=17940"><?php _e( 'Report a Bug', 'cuttz-framework' ); ?></a></li>
			
			<!-- Showcase your site built on Cuttz -->
			<li><span class="dashicons dashicons-twitter"></span><a class="cuttz-admin-help" href="https://twitter.com/intent/tweet?text=Here%27s+my+new+design+built+on+Cuttz+Framework+&nbsp;&amp;url=<?php echo get_site_url(); ?>&amp;hashtags=cuttzwp&amp;via=shivanandwp" target="_blank"><?php _e( 'Tweet us your new design', 'cuttz-framework' ); ?></a></li>

			</ul>
			</div>
			</div>
			
			<!-- Cuttz Testimonials Metabox -->
			
			<div class="cuttz-testimonial-area section">
			<h3><?php _e( 'Share Your Success Story', 'cuttz-framework' ); ?></h3>
			<div class="cuttz-postbox-wrapper">
			<p><?php printf( __( 'Share you success story with Cuttz Framework. And we may even feature you in our %sfeatured developers%s list!', 'cuttz-framework' ), '<a class="cuttz-featured-devs" href="https://www.binaryturf.com/?p=18272">', '</a>' ); ?></p>
			<p class="cuttz-testimonial-cta"><a class="cuttz-submit-testimonial" title="Share Your Experience" href="https://www.binaryturf.com/?p=18130"><?php _e( 'Share your success story!', 'cuttz-framework' ); ?></a></p>
			<p class="cuttz-sb-sm"><?php printf( __( '%s%s%s', 'cuttz-framework' ), '<a title="Twitter" class="cuttz-follow-sm" href="https://twitter.com/shivanandwp"><span class="dashicons dashicons-twitter"></span></a>', '<a title="Facebook" class="cuttz-follow-sm" href="https://www.facebook.com/binaryturf"><span class="dashicons dashicons-facebook-alt"></span></a>', '<a title="Google+" class="cuttz-follow-sm" href="https://plus.google.com/+binaryturf"><span class="dashicons dashicons-googleplus"></span></a>' ); ?></p>
			</div>
			</div>
		</div>
	<?php

}


add_action( 'admin_head', 'cuttz_help_area_styles' );

/**
 * WordPress scheme specific styles for Cuttz help area
 * @return none
 * @since 1.0
 */
function cuttz_help_area_styles() {

	$current_color_scheme = cuttz_get_admin_color_scheme();

	if ( !$current_color_scheme )
		return;

	$active_colors      = $current_color_scheme->colors;
	$active_theme_color = $active_colors[1];
	$active_cta_color   = $active_colors[3];

	if ( $active_theme_color ) {
		echo '
			<style type="text/css">
				.cuttz-framework .cuttz-sidebar h3 {
					bbackground-color: ' . $active_theme_color . ';
					color: #ffffff;
				}
			</style>
		';
	}

}

/**
 * Helper function to get the admin area color scheme set by the current user.
 * @return ?
 * @since 1.0
 */
function cuttz_get_admin_color_scheme() {

	$current_color = get_user_option( 'admin_color' );
	global $_wp_admin_css_colors;
	$current_scheme = array();
	$colors         = $_wp_admin_css_colors;

	if ( array_key_exists( $current_color, $colors ) ) {
		$current_scheme = $colors[$current_color];
	}

	return $current_scheme;

}


/**
 * Helper function that validates a CSS usable color
 * @param string $clr 
 * @param string $def 
 * @return string
 */
function cuttz_validate_color( $clr, $def ) {
	$clrnames = array(
		'transparent',
		'aliceblue',
		'antiquewhite',
		'aqua',
		'aquamarine',
		'azure',
		'beige',
		'bisque',
		'black',
		'blanchedalmond',
		'blue',
		'blueviolet',
		'brown',
		'burlywood',
		'cadetblue',
		'chartreuse',
		'chocolate',
		'coral',
		'cornflowerblue',
		'cornsilk',
		'crimson',
		'cyan',
		'darkblue',
		'darkcyan',
		'darkgoldenrod',
		'darkgray',
		'darkgreen',
		'darkkhaki',
		'darkmagenta',
		'darkolivegreen',
		'darkorange',
		'darkorchid',
		'darkred',
		'darksalmon',
		'darkseagreen',
		'darkslateblue',
		'darkslategray',
		'darkturquoise',
		'darkviolet',
		'deeppink',
		'deepskyblue',
		'dimgray',
		'dodgerblue',
		'firebrick',
		'floralwhite',
		'forestgreen',
		'fuchsia',
		'gainsboro',
		'ghostwhite',
		'gold',
		'goldenrod',
		'gray',
		'green',
		'greenyellow',
		'honeydew',
		'hotpink',
		'indianred',
		'indigo',
		'ivory',
		'khaki',
		'lavender',
		'lavenderblush',
		'lawngreen',
		'lemonchiffon',
		'lightblue',
		'lightcoral',
		'lightcyan',
		'lightgoldenrodyellow',
		'lightgray',
		'lightgreen',
		'lightpink',
		'lightsalmon',
		'lightseagreen',
		'lightskyblue',
		'lightslategray',
		'lightsteelblue',
		'lightyellow',
		'lime',
		'limegreen',
		'linen',
		'magenta',
		'maroon',
		'mediumaquamarine',
		'mediumblue',
		'mediumorchid',
		'mediumpurple',
		'mediumseagreen',
		'mediumslateblue',
		'mediumspringgreen',
		'mediumturquoise',
		'mediumvioletred',
		'midnightblue',
		'mintcream',
		'mistyrose',
		'moccasin',
		'navajowhite',
		'navy',
		'oldlace',
		'olive',
		'olivedrab',
		'orange',
		'orangered',
		'orchid',
		'palegoldenrod',
		'palegreen',
		'paleturquoise',
		'palevioletred',
		'papayawhip',
		'peachpuff',
		'peru',
		'pink',
		'plum',
		'powderblue',
		'purple',
		'red',
		'rosybrown',
		'royalblue',
		'saddlebrown',
		'salmon',
		'sandybrown',
		'seagreen',
		'seashell',
		'sienna',
		'silver',
		'skyblue',
		'slateblue',
		'slategray',
		'snow',
		'springgreen',
		'steelblue',
		'tan',
		'teal',
		'thistle',
		'tomato',
		'turquoise',
		'violet',
		'wheat',
		'white',
		'whitesmoke',
		'yellow',
		'yellowgreen'
	);

	$clr = strtolower( $clr );
	if ( preg_match( '/rgba?\((\s+)?\d+(\s+)?,(\s+)?\d+(\s+)?,(\s+)?\d+(\s+)?,\d*(?:\.\d+)?\)/i', $clr ) ) {
		return $clr;
	}

	// Try validating hex
	//can also replace /(#.*?)(([0-9a-f]{3}){1,2})/ with $2???
	preg_match( '/(([0-9a-f]{3}){1,2})/i', $clr, $matches );

	if ( $matches ) {
		return '#' . $matches[0];
	}

	if ( in_array( $clr, $clrnames ) ) {
		return $clr;
	}

	return $def;
}

add_action( 'genesis_after_content', 'cuttz_clear_csb_wrap', 10 );

/**
 * Fix the uncleared content and sidebar columns in Genesis
 * @return none
 * @since 1.0
 */
function cuttz_clear_csb_wrap() {
	echo '<div class="clear"></div>';
}

/**
 * Wrapper for genesis breadcrumbs functions so that the theme options have control over breacrumbs display
 * @return none
 * @since 1.0
 */
function cuttz_do_breadcrumbs() {

	$display_breadcrumbs = apply_filters( 'cuttz_do_breadcrumbs', true );

	if ( $display_breadcrumbs )
		genesis_do_breadcrumbs();

}


/**
 * Adds cuttz-alignnone class to content archives featured image if alignment is set as none. Helps tweak the typography/spacing with CSS
 * @param array $attributes 
 * @return array
 */
function cuttz_attributes_entry_image( $attributes ) {
	$alignment = genesis_get_option( 'image_alignment' );
	if ( empty( $alignment ) ) {
		$attributes['class'] = $attributes['class'] . ' cuttz-alignnone';
	}
	return $attributes;
}

/**
 * Wrapper function for woocommerce 'is_shop' function
 * @return none
 * @since 1.0
 */

function cuttz_is_woo_shop() {
	if ( in_array( 'woocommerce/woocommerce.php', get_option( 'active_plugins' ) ) ) {
		if( is_shop() ) {
			return true;
		}
	}
}
